### ISSUE TITLE
Fix entries for originator

### ISSUE THREAD

**Issue by joergreichert** [CodeforLeipzig/stadtratmonitor#29]
currently the entries are: dezernat, fraktion, und, die bau, stadtentwicklung, linke, gesundheit, jugend, soziales

Performing the following query against SQLite database
`select originator, count(name) as paper_count from papers group by originator having paper_count > 1 order by paper_count desc`

gives: 
[originator.xlsx](https://github.com/CodeforLeipzig/stadtratmonitor/files/190536/originator.xlsx)

**Comment by joergreichert** [comment]
This could be maybe fixed by deactivating the tokenizer / analyzer for field originator in ElasticSearch mapping

**Comment by jrlover** [comment]
was already fixed by adding not_analyzed. Had forgotten to rebuild the index.
